name: Publish
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - ci/github_actions # temporary

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-bundle:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install
        timeout-minutes: 3
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Download Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0

      - name: Prepare credentials
        id: prepare-credentials
        timeout-minutes: 1
        run: |
          echo "${KEYSTORE_ENCODED}" | base64 -d > upload_keystore.jks
          echo "upload_store_file=$(realpath upload_keystore.jks)" >> "${GITHUB_OUTPUT}"
          echo "${KEY_JSON_ENCODED}" | base64 -d > sa.json
          echo "sa_json_file=$(realpath sa.json)" >> "${GITHUB_OUTPUT}"
        env:
          KEYSTORE_ENCODED: ${{ secrets.UPLOAD_KEYSTORE }}
          KEY_JSON_ENCODED: ${{ secrets.KEY_JSON }}

      - name: Grant permission of Gradle wrapper
        timeout-minutes: 1
        run: chmod +x gradlew

      - name: Build Release AAB
        timeout-minutes: 12
        run: |
          ./gradlew publishReleaseBundle
        env:
          _JAVA_OPTIONS: '-Duser.language=ja -Duser.country=JP'
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          STORE_FILE_PATH: ${{ steps.prepare-credentials.outputs.upload_store_file }}
          SA_FILE_PATH: ${{ steps.prepare-credentials.outputs.sa_json_file }}

      - name: Clean up credentials
        timeout-minutes: 1
        if: ${{ always() }}
        run: |
          rm upload_keystore.jks
          rm sa.json

      - name: Upload artifacts
        timeout-minutes: 2
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Release bundle artifacts
          path: |
            app/build/outputs/

      - name: Upload AAB to artifact
        timeout-minutes: 2
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Release AAB
          path: |
            app/build/outputs/bundle/release/*.aab

      - name: Upload Kotlin build report
        timeout-minutes: 2
        uses: actions/upload-artifact@v4
        with:
          name: Kotlin build report-bundle
          path: |
            build/reports/kotlin-build
